# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFormLayout, QFrame,
    QGroupBox, QHBoxLayout, QHeaderView, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QRadioButton, QSizePolicy, QSpinBox, QStatusBar,
    QTabWidget, QTreeWidget, QTreeWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1034, 600)
        MainWindow.setMinimumSize(QSize(1034, 0))
        self.action_Open = QAction(MainWindow)
        self.action_Open.setObjectName(u"action_Open")
        self.action_Save = QAction(MainWindow)
        self.action_Save.setObjectName(u"action_Save")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.action_Quit = QAction(MainWindow)
        self.action_Quit.setObjectName(u"action_Quit")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.formLayout = QFormLayout()
        self.formLayout.setObjectName(u"formLayout")
        self.treeWidget = QTreeWidget(self.centralwidget)
        QTreeWidgetItem(self.treeWidget)
        QTreeWidgetItem(self.treeWidget)
        QTreeWidgetItem(self.treeWidget)
        QTreeWidgetItem(self.treeWidget)
        self.treeWidget.setObjectName(u"treeWidget")
        self.treeWidget.setMinimumSize(QSize(300, 0))

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.treeWidget)

        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QSize(700, 520))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 58, 21))
        self.si_name = QLineEdit(self.tab)
        self.si_name.setObjectName(u"si_name")
        self.si_name.setGeometry(QRect(90, 0, 221, 21))
        self.si_name.setMaxLength(10)
        self.label_2 = QLabel(self.tab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 58, 21))
        self.line = QFrame(self.tab)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 20, 681, 16))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.si_volume = QSpinBox(self.tab)
        self.si_volume.setObjectName(u"si_volume")
        self.si_volume.setGeometry(QRect(90, 40, 42, 22))
        self.si_volume.setMaximum(100)
        self.label_3 = QLabel(self.tab)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(150, 40, 41, 21))
        self.si_effect = QSpinBox(self.tab)
        self.si_effect.setObjectName(u"si_effect")
        self.si_effect.setGeometry(QRect(210, 40, 42, 22))
        self.si_effect.setMinimum(1)
        self.si_effect.setMaximum(32)
        self.label_4 = QLabel(self.tab)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 70, 71, 21))
        self.si_out_select = QSpinBox(self.tab)
        self.si_out_select.setObjectName(u"si_out_select")
        self.si_out_select.setGeometry(QRect(90, 70, 42, 22))
        self.si_out_select.setMaximum(7)
        self.si_source_mode = QGroupBox(self.tab)
        self.si_source_mode.setObjectName(u"si_source_mode")
        self.si_source_mode.setGeometry(QRect(270, 40, 120, 81))
        self.si_sm_norm = QRadioButton(self.si_source_mode)
        self.si_sm_norm.setObjectName(u"si_sm_norm")
        self.si_sm_norm.setGeometry(QRect(0, 20, 99, 20))
        self.si_sm_twin = QRadioButton(self.si_source_mode)
        self.si_sm_twin.setObjectName(u"si_sm_twin")
        self.si_sm_twin.setGeometry(QRect(0, 40, 99, 20))
        self.si_sm_double = QRadioButton(self.si_source_mode)
        self.si_sm_double.setObjectName(u"si_sm_double")
        self.si_sm_double.setGeometry(QRect(0, 60, 99, 20))
        self.si_poly_mode = QGroupBox(self.tab)
        self.si_poly_mode.setObjectName(u"si_poly_mode")
        self.si_poly_mode.setGeometry(QRect(410, 40, 81, 101))
        self.si_pm_poly1 = QRadioButton(self.si_poly_mode)
        self.si_pm_poly1.setObjectName(u"si_pm_poly1")
        self.si_pm_poly1.setGeometry(QRect(0, 20, 99, 20))
        self.si_pm_poly2 = QRadioButton(self.si_poly_mode)
        self.si_pm_poly2.setObjectName(u"si_pm_poly2")
        self.si_pm_poly2.setGeometry(QRect(0, 40, 99, 20))
        self.si_pm_solo1 = QRadioButton(self.si_poly_mode)
        self.si_pm_solo1.setObjectName(u"si_pm_solo1")
        self.si_pm_solo1.setGeometry(QRect(0, 60, 99, 20))
        self.si_pm_solo2 = QRadioButton(self.si_poly_mode)
        self.si_pm_solo2.setObjectName(u"si_pm_solo2")
        self.si_pm_solo2.setGeometry(QRect(0, 80, 99, 20))
        self.groupBox = QGroupBox(self.tab)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(510, 40, 81, 101))
        self.si_mute_s1 = QCheckBox(self.groupBox)
        self.si_mute_s1.setObjectName(u"si_mute_s1")
        self.si_mute_s1.setGeometry(QRect(10, 20, 85, 20))
        self.si_mute_s2 = QCheckBox(self.groupBox)
        self.si_mute_s2.setObjectName(u"si_mute_s2")
        self.si_mute_s2.setGeometry(QRect(10, 40, 85, 20))
        self.si_mute_s3 = QCheckBox(self.groupBox)
        self.si_mute_s3.setObjectName(u"si_mute_s3")
        self.si_mute_s3.setGeometry(QRect(10, 60, 85, 20))
        self.si_mute_s4 = QCheckBox(self.groupBox)
        self.si_mute_s4.setObjectName(u"si_mute_s4")
        self.si_mute_s4.setGeometry(QRect(10, 80, 85, 20))
        self.groupBox_2 = QGroupBox(self.tab)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(520, 150, 161, 41))
        self.si_am_s12 = QCheckBox(self.groupBox_2)
        self.si_am_s12.setObjectName(u"si_am_s12")
        self.si_am_s12.setGeometry(QRect(0, 20, 85, 20))
        self.si_am_s34 = QCheckBox(self.groupBox_2)
        self.si_am_s34.setObjectName(u"si_am_s34")
        self.si_am_s34.setGeometry(QRect(80, 20, 85, 20))
        self.groupBox_3 = QGroupBox(self.tab)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(500, 230, 120, 101))
        self.radioButton = QRadioButton(self.groupBox_3)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(0, 20, 99, 20))
        self.radioButton_2 = QRadioButton(self.groupBox_3)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setGeometry(QRect(0, 40, 99, 20))
        self.radioButton_3 = QRadioButton(self.groupBox_3)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setGeometry(QRect(0, 60, 99, 20))
        self.radioButton_4 = QRadioButton(self.groupBox_3)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setGeometry(QRect(0, 80, 99, 20))
        self.groupBox_4 = QGroupBox(self.tab)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(320, 240, 120, 80))
        self.radioButton_5 = QRadioButton(self.groupBox_4)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setGeometry(QRect(0, 20, 99, 20))
        self.radioButton_6 = QRadioButton(self.groupBox_4)
        self.radioButton_6.setObjectName(u"radioButton_6")
        self.radioButton_6.setGeometry(QRect(0, 40, 99, 20))
        self.radioButton_7 = QRadioButton(self.groupBox_4)
        self.radioButton_7.setObjectName(u"radioButton_7")
        self.radioButton_7.setGeometry(QRect(0, 60, 99, 20))
        self.label_5 = QLabel(self.tab)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 110, 71, 21))
        self.si_pitch_bend = QSpinBox(self.tab)
        self.si_pitch_bend.setObjectName(u"si_pitch_bend")
        self.si_pitch_bend.setGeometry(QRect(100, 110, 42, 22))
        self.si_pitch_bend.setMaximum(12)
        self.label_6 = QLabel(self.tab)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 140, 91, 21))
        self.si_vib_speed = QSpinBox(self.tab)
        self.si_vib_speed.setObjectName(u"si_vib_speed")
        self.si_vib_speed.setGeometry(QRect(120, 140, 42, 22))
        self.si_vib_speed.setMaximum(100)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.tabWidget)


        self.horizontalLayout.addLayout(self.formLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1034, 24))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addAction(self.actionSave_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Quit)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.action_Open.setText(QCoreApplication.translate("MainWindow", u"&Open", None))
#if QT_CONFIG(shortcut)
        self.action_Open.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_Save.setText(QCoreApplication.translate("MainWindow", u"&Save", None))
#if QT_CONFIG(shortcut)
        self.action_Save.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save &As", None))
#if QT_CONFIG(shortcut)
        self.actionSave_As.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+A", None))
#endif // QT_CONFIG(shortcut)
        self.action_Quit.setText(QCoreApplication.translate("MainWindow", u"&Quit", None))
        ___qtreewidgetitem = self.treeWidget.headerItem()
        ___qtreewidgetitem.setText(0, QCoreApplication.translate("MainWindow", u"Data", None));

        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        ___qtreewidgetitem1 = self.treeWidget.topLevelItem(0)
        ___qtreewidgetitem1.setText(0, QCoreApplication.translate("MainWindow", u"Single Instruments", None));
        ___qtreewidgetitem2 = self.treeWidget.topLevelItem(1)
        ___qtreewidgetitem2.setText(0, QCoreApplication.translate("MainWindow", u"Multiple Instruments", None));
        ___qtreewidgetitem3 = self.treeWidget.topLevelItem(2)
        ___qtreewidgetitem3.setText(0, QCoreApplication.translate("MainWindow", u"Drums", None));
        ___qtreewidgetitem4 = self.treeWidget.topLevelItem(3)
        ___qtreewidgetitem4.setText(0, QCoreApplication.translate("MainWindow", u"Effects", None));
        self.treeWidget.setSortingEnabled(__sortingEnabled)

        self.label.setText(QCoreApplication.translate("MainWindow", u"Name:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Volume:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Effect:", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Out Select:", None))
        self.si_source_mode.setTitle(QCoreApplication.translate("MainWindow", u"Source mode:", None))
        self.si_sm_norm.setText(QCoreApplication.translate("MainWindow", u"Normal", None))
        self.si_sm_twin.setText(QCoreApplication.translate("MainWindow", u"Twin", None))
        self.si_sm_double.setText(QCoreApplication.translate("MainWindow", u"Double", None))
        self.si_poly_mode.setTitle(QCoreApplication.translate("MainWindow", u"Poly mode:", None))
        self.si_pm_poly1.setText(QCoreApplication.translate("MainWindow", u"Poly 1", None))
        self.si_pm_poly2.setText(QCoreApplication.translate("MainWindow", u"Poly 2", None))
        self.si_pm_solo1.setText(QCoreApplication.translate("MainWindow", u"Solo 1", None))
        self.si_pm_solo2.setText(QCoreApplication.translate("MainWindow", u"Solo 2", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Mute:", None))
        self.si_mute_s1.setText(QCoreApplication.translate("MainWindow", u"S1", None))
        self.si_mute_s2.setText(QCoreApplication.translate("MainWindow", u"S2", None))
        self.si_mute_s3.setText(QCoreApplication.translate("MainWindow", u"S3", None))
        self.si_mute_s4.setText(QCoreApplication.translate("MainWindow", u"S4", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"AM:", None))
        self.si_am_s12.setText(QCoreApplication.translate("MainWindow", u"S1 > S2", None))
        self.si_am_s34.setText(QCoreApplication.translate("MainWindow", u"S3 > S4", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Vibrato shape:", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"Triangle", None))
        self.radioButton_2.setText(QCoreApplication.translate("MainWindow", u"Saw", None))
        self.radioButton_3.setText(QCoreApplication.translate("MainWindow", u"Square", None))
        self.radioButton_4.setText(QCoreApplication.translate("MainWindow", u"Random", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Wheel assign:", None))
        self.radioButton_5.setText(QCoreApplication.translate("MainWindow", u"Vibrato", None))
        self.radioButton_6.setText(QCoreApplication.translate("MainWindow", u"LFO", None))
        self.radioButton_7.setText(QCoreApplication.translate("MainWindow", u"DCF", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Pitch bend:", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Vibrato speed:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Single Instrument", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
    # retranslateUi

